import os
import json

# ---- 1) Copy your plotData array here (shortened example) ----
plotData = [
  {
    "labelName": "BaBar", 
    "longName": "BaBar", 
    "id": "babar",
    "text": { "elementName": None  }, 
    "line": { "color": "gray", "dash": None , "width": 2 }, 
    "area": { "color": "lightgray" }, 
    "paperUrls": ["https://arxiv.org/abs/1406.2980"], 
    "url": "../../data/BC1/BaBar.csv", 
    "curveType": "excluded",
    "categories": {
      "detectionType": "Direct detection",
      "experimentType": "Collider experiments",
      "timeType": "Past constraints",
      "assumption": "None",
    }, 
  },
  {
    "labelName": "AFM test", 
    "longName": "AFM test of Coulomb force", 
    "id": "afm-test",
    "text": { "elementName": None  }, 
    "line": { "color": "rgba(5, 58, 133, 1)", "dash": None , "width": 2 },
    "area": { "color": "rgba(57, 130, 232, 1)" },
    "paperUrls": ["https://arxiv.org/abs/2008.02209"],
    "url": "../../data/BC1/AFM.csv",
    "curveType": "excluded",
    "categories": {
      "detectionType": "Direct detection",
      "experimentType": "Laboratory experiments",
      "timeType": "Recent constraints",
      "assumption": "None",
    }, 
  },
  {
    "labelName": "ALPS", 
    "longName": "ALPS", 
    "id": "alps",
    "text": { "elementName": None  }, 
    "line": { "color": "rgba(5, 58, 133, 1)", "dash": None , "width": 2 },
    "area": { "color": "rgba(57, 130, 232, 1)" },
    "paperUrls": ["https://arxiv.org/abs/1004.1313"],
    "url": "../../data/BC1/ALPS.csv",
    "curveType": "excluded",
    "categories": {
      "detectionType": "Direct detection",
      "experimentType": "Laboratory experiments",
      "timeType": "Past constraints",
      "assumption": "None",
    }, 
  },
  {
    "labelName": "AMAILS", 
    "longName": "AMAILS", 
    "id": "amails",
    "text": { "elementName": None  }, 
    "line": { "color": "rgba(5, 58, 133, 1)", "dash": None , "width": 2 },
    "area": { "color": "rgba(57, 130, 232, 1)" },
    "paperUrls": ["https://arxiv.org/abs/2305.00890"],
    "url": "../../data/BC1/AMAILS.csv",
    "curveType": "excluded",
    "categories": {
      "detectionType": "Direct detection",
      "experimentType": "Laboratory experiments",
      "timeType": "Recent constraints",
      "assumption": "Dark Matter",
    }, 
  },
  {
    "labelName": "Arias et al. (2012)", 
    "longName": "Arias et al. (2012) (Cosmology)", 
    "id": "arias2012",
    "text": { "elementName": None  }, 
    "line": { "color": "rgba(5, 58, 133, 1)", "dash": None , "width": 2 },
    "area": { "color": "rgba(57, 130, 232, 1)" },
    "paperUrls": ["https://arxiv.org/abs/1201.5902"],
    "url": "../../data/BC1/Cosmology_Arias.csv",
    "curveType": "excluded",
    "categories": {
      "detectionType": "Indirect detection",
      "experimentType": "Astrophysical observations",
      "timeType": "Past constraints",
      "assumption": "Dark Matter",
    }, 
  },
  {
    "labelName": "Caputo et al. (2020)", 
    "longName": "Caputo et al. (2020) (HeII reionisation)", 
    "id": "Caputo2020",
    "text": { "elementName": None  }, 
    "line": { "color": "rgba(5, 58, 133, 1)", "dash": None , "width": 2 },
    "area": { "color": "rgba(57, 130, 232, 1)" },
    "paperUrls": ["https://arxiv.org/abs/2002.05165"],
    "url": "../../data/BC1/Cosmology_Caputo_HeII_.csv",
    "curveType": "excluded",
    "categories": {
      "detectionType": "Indirect detection",
      "experimentType": "Cosmological measurements",
      "timeType": "Recent constraints",
      "assumption": "Dark Matter",
    }, 
  },
  {
    "labelName": "Witte et al. (2020)", 
    "longName": "Witte et al. (2020) (inhomogeneous plasma)", 
    "id": "witte2020",
    "text": { "elementName": None  }, 
    "line": { "color": "rgba(5, 58, 133, 1)", "dash": None , "width": 2 },
    "area": { "color": "rgba(57, 130, 232, 1)" },
    "paperUrls": ["https://arxiv.org/abs/2003.13698"],
    "url": "../../data/BC1/Cosmology_Witte_inhomogeneous.csv",
    "curveType": "excluded",
    "categories": {
      "detectionType": "Indirect detection",
      "experimentType": "Cosmological measurements",
      "timeType": "Recent constraints",
      "assumption": "Dark Matter",
    }, 
  },
  {
    "labelName": "Crab Nebula", 
    "longName": "Crab Nebula", 
    "id": "crab-nebula",
    "text": { "elementName": None  }, 
    "line": { "color": "rgba(5, 58, 133, 1)", "dash": None , "width": 2 },
    "area": { "color": "rgba(57, 130, 232, 1)" },
    "paperUrls": ["https://arxiv.org/abs/0810.5501"],
    "url": "../../data/BC1/Crab.csv",
    "curveType": "excluded",
    "categories": {
      "detectionType": "Indirect detection",
      "experimentType": "Astrophysical observations",
      "timeType": "Past constraints",
      "assumption": "None",
    }, 
  },
  {
    "labelName": "CROWS", 
    "longName": "CROWS", 
    "id": "crows",
    "text": { "elementName": None  }, 
    "line": { "color": "rgba(5, 58, 133, 1)", "dash": None , "width": 2 },
    "area": { "color": "rgba(57, 130, 232, 1)" },
    "paperUrls": ["https://arxiv.org/abs/1310.8098"],
    "url": "../../data/BC1/CROWS.csv",
    "curveType": "excluded",
    "categories": {
      "detectionType": "Direct detection",
      "experimentType": "Laboratory experiments",
      "timeType": "Past constraints",
      "assumption": "None",
    }, 
  },
  {
    "labelName": "DAMIC", 
    "longName": "DAMIC", 
    "id": "damic",
    "text": { "elementName": None  }, 
    "line": { "color": "rgba(5, 58, 133, 1)", "dash": None , "width": 2 },
    "area": { "color": "rgba(57, 130, 232, 1)" },
    "paperUrls": ["https://arxiv.org/abs/1907.12628"],
    "url": "../../data/BC1/DAMIC.csv",
    "curveType": "excluded",
    "categories": {
      "detectionType": "Direct detection",
      "experimentType": "Laboratory experiments",
      "timeType": "Recent constraints",
      "assumption": "Dark Matter",
    }, 
  },
  {
    "labelName": "DarkSide-50", 
    "longName": "DarkSide-50", 
    "id": "darkside-50",
    "text": { "elementName": None  }, 
    "line": { "color": "rgba(5, 58, 133, 1)", "dash": None , "width": 2 },
    "area": { "color": "rgba(57, 130, 232, 1)" },
    "paperUrls": ["https://arxiv.org/abs/2207.11968"],
    "url": "../../data/BC1/DarkSide.csv",
    "curveType": "excluded",
    "categories": {
      "detectionType": "Direct detection",
      "experimentType": "Laboratory experiments",
      "timeType": "Recent constraints",
      "assumption": "Dark Matter",
    }, 
  },
  {
    "labelName": "Dark SRF", 
    "longName": "Dark SRF", 
    "id": "dark-srf",
    "text": { "elementName": None  }, 
    "line": { "color": "rgba(5, 58, 133, 1)", "dash": None , "width": 2 },
    "area": { "color": "rgba(57, 130, 232, 1)" },
    "paperUrls": ["https://arxiv.org/abs/2301.11512"],
    "url": "../../data/BC1/DarkSRF.csv",
    "curveType": "excluded",
    "categories": {
      "detectionType": "Direct detection",
      "experimentType": "Laboratory experiments",
      "timeType": "Recent constraints",
      "assumption": "None",
    }, 
  },
  {
    "labelName": "Haloscopes 1", 
    "longName": "Haloscopes 1", 
    "id": "haloscopes1",
    "text": { "elementName": None  }, 
    "line": { "color": "rgba(5, 58, 133, 1)", "dash": None , "width": 2 },
    "area": { "color": "rgba(57, 130, 232, 1)" },
    "paperUrls": ["https://arxiv.org/abs/2105.04565"],
    "url": "../../data/BC1/DP_Combined_AxionSearchesRescaled.csv",
    "curveType": "excluded",
    "categories": {
      "detectionType": "Indirect detection",
      "experimentType": "Laboratory experiments",
      "timeType": "Recent constraints",
      "assumption": "Dark Matter",
    }, 
  },
  {
    "labelName": "Haloscopes 2", 
    "longName": "Haloscopes 2", 
    "id": "haloscopes2",
    "text": { "elementName": None  }, 
    "line": { "color": "rgba(5, 58, 133, 1)", "dash": None , "width": 2 },
    "area": { "color": "rgba(57, 130, 232, 1)" },
    "paperUrls": ["https://arxiv.org/abs/2105.04565"],
    "url": "../../data/BC1/DP_Combined_DarkMatterSearches.csv",
    "curveType": "excluded",
    "categories": {
      "detectionType": "Indirect detection",
      "experimentType": "Laboratory experiments",
      "timeType": "Recent constraints",
      "assumption": "Dark Matter",
    }, 
  },
  {
    "labelName": "Earth", 
    "longName": "Earth", 
    "id": "earth",
    "text": { "elementName": None  }, 
    "line": { "color": "rgba(5, 58, 133, 1)", "dash": None , "width": 2 },
    "area": { "color": "rgba(57, 130, 232, 1)" },
    "paperUrls": ["https://arxiv.org/abs/2110.02875"],
    "url": "../../data/BC1/Earth.csv",
    "curveType": "excluded",
    "categories": {
      "detectionType": "Indirect detection",
      "experimentType": "Astrophysical observations",
      "timeType": "Recent constraints",
      "assumption": "None",
    }, 
  },
  {
    "labelName": "FUNK", 
    "longName": "FUNK", 
    "id": "funk",
    "text": { "elementName": None  }, 
    "line": { "color": "rgba(5, 58, 133, 1)", "dash": None , "width": 2 },
    "area": { "color": "rgba(57, 130, 232, 1)" },
    "paperUrls": ["https://arxiv.org/abs/2003.13144"],
    "url": "../../data/BC1/FUNK.csv",
    "curveType": "excluded",
    "categories": {
      "detectionType": "Direct detection",
      "experimentType": "Laboratory experiments",
      "timeType": "Recent constraints",
      "assumption": "None",
    }, 
  },
  {
    "labelName": "G33.4-8.0", 
    "longName": "G33.4-8.0", 
    "id": "g33",
    "text": { "elementName": None  }, 
    "line": { "color": "rgba(5, 58, 133, 1)", "dash": None , "width": 2 },
    "area": { "color": "rgba(57, 130, 232, 1)" },
    "paperUrls": ["https://arxiv.org/abs/1903.12190"],
    "url": "../../data/BC1/GasClouds.csv",
    "curveType": "excluded",
    "categories": {
      "detectionType": "Indirect detection",
      "experimentType": "Astrophysical observations",
      "timeType": "Recent constraints",
      "assumption": "Dark Matter",
    }, 
  },
  {
    "labelName": "Globular Clusters", 
    "longName": "Globular Clusters", 
    "id": "globular-clusters",
    "text": { "elementName": None  }, 
    "line": { "color": "rgba(5, 58, 133, 1)", "dash": None , "width": 2 },
    "area": { "color": "rgba(57, 130, 232, 1)" },
    "paperUrls": ["https://arxiv.org/abs/2306.13335"],
    "url": "../../data/BC1/GlobularClusters.csv",
    "curveType": "excluded",
    "categories": {
      "detectionType": "Indirect detection",
      "experimentType": "Astrophysical observations",
      "timeType": "Recent constraints",
      "assumption": "None",
    }, 
  },
  {
    "labelName": "Hinode", 
    "longName": "Hinode", 
    "id": "hinode",
    "text": { "elementName": None  }, 
    "line": { "color": "rgba(5, 58, 133, 1)", "dash": None , "width": 2 },
    "area": { "color": "rgba(57, 130, 232, 1)" },
    "paperUrls": ["https://arxiv.org/abs/2211.00022"],
    "url": "../../data/BC1/HINODE.csv",
    "curveType": "excluded",
    "categories": {
      "detectionType": "Indirect detection",
      "experimentType": "Astrophysical observations",
      "timeType": "Recent constraints",
      "assumption": "None",
    }, 
  },
  {
    "labelName": "INTEGRAL", 
    "longName": "INTEGRAL", 
    "id": "integral",
    "text": { "elementName": None  }, 
    "line": { "color": "rgba(5, 58, 133, 1)", "dash": None , "width": 2 },
    "area": { "color": "rgba(57, 130, 232, 1)" },
    "paperUrls": [
      "https://arxiv.org/abs/2406.19445",
      "https://arxiv.org/abs/2412.00180",
    ],
    "url": "../../data/BC1/INTEGRAL.csv",
    "curveType": "excluded",
    "categories": {
      "detectionType": "Indirect detection",
      "experimentType": "Astrophysical observations",
      "timeType": "Recent constraints",
      "assumption": "Dark Matter",
    }, 
  },
  {
    "labelName": "Jupiter", 
    "longName": "Jupiter", 
    "id": "jupiter",
    "text": { "elementName": None  }, 
    "line": { "color": "rgba(5, 58, 133, 1)", "dash": None , "width": 2 },
    "area": { "color": "rgba(57, 130, 232, 1)" },
    "paperUrls": ["https://arxiv.org/abs/2312.06746"],
    "url": "../../data/BC1/Jupiter.csv",
    "curveType": "excluded",
    "categories": {
      "detectionType": "Indirect detection",
      "experimentType": "Astrophysical observations",
      "timeType": "Recent constraints",
      "assumption": "None",
    }, 
  },
  {
    "labelName": "JWST", 
    "longName": "JWST", 
    "id": "jwst",
    "text": { "elementName": None  }, 
    "line": { "color": "rgba(5, 58, 133, 1)", "dash": None , "width": 2 },
    "area": { "color": "rgba(57, 130, 232, 1)" },
    "paperUrls": ["https://arxiv.org/abs/2402.17140"],
    "url": "../../data/BC1/JWST.csv",
    "curveType": "excluded",
    "categories": {
      "detectionType": "Direct detection",
      "experimentType": "Laboratory experiments",
      "timeType": "Recent constraints",
      "assumption": "Dark Matter",
    }, 
  },
  {
    "labelName": "Leo T", 
    "longName": "Leo T", 
    "id": "leo-t",
    "text": { "elementName": None  }, 
    "line": { "color": "rgba(5, 58, 133, 1)", "dash": None , "width": 2 },
    "area": { "color": "rgba(57, 130, 232, 1)" },
    "paperUrls": ["https://arxiv.org/abs/1903.12190"],
    "url": "../../data/BC1/LeoT.csv",
    "curveType": "excluded",
    "categories": {
      "detectionType": "Indirect detection",
      "experimentType": "Astrophysical observations",
      "timeType": "Recent constraints",
      "assumption": "Dark Matter",
    }, 
  },
  {
    "labelName": "ADMX", 
    "longName": "ADMX", 
    "id": "admx",
    "text": { "elementName": None  }, 
    "line": { "color": "rgba(5, 58, 133, 1)", "dash": None , "width": 2 },
    "area": { "color": "rgba(57, 130, 232, 1)" },
    "paperUrls": ["https://arxiv.org/abs/1007.3766"],
    "url": "../../data/BC1/LSW_ADMX.csv",
    "curveType": "excluded",
    "categories": {
      "detectionType": "Direct detection",
      "experimentType": "Laboratory experiments",
      "timeType": "Past constraints",
      "assumption": "None",
    }, 
  },
  {
    "labelName": "UWA", 
    "longName": "UWA", 
    "id": "uwa",
    "text": { "elementName": None  }, 
    "line": { "color": "rgba(5, 58, 133, 1)", "dash": None , "width": 2 },
    "area": { "color": "rgba(57, 130, 232, 1)" },
    "paperUrls": ["https://arxiv.org/abs/1410.5244"],
    "url": "../../data/BC1/LSW_UWA.csv",
    "curveType": "excluded",
    "categories": {
      "detectionType": "Direct detection",
      "experimentType": "Laboratory experiments",
      "timeType": "Past constraints",
      "assumption": "None",
    }, 
  },
  {
    "labelName": "MuDHI", 
    "longName": "MuDHI", 
    "id": "mudhi",
    "text": { "elementName": None  }, 
    "line": { "color": "rgba(5, 58, 133, 1)", "dash": None , "width": 2 },
    "area": { "color": "rgba(57, 130, 232, 1)" },
    "paperUrls": ["https://arxiv.org/abs/2110.10497"],
    "url": "../../data/BC1/MuDHI.csv",
    "curveType": "excluded",
    "categories": {
      "detectionType": "Direct detection",
      "experimentType": "Laboratory experiments",
      "timeType": "Recent constraints",
      "assumption": "Dark Matter",
    }, 
  },
  {
    "labelName": "Cas A", 
    "longName": "Cas A", 
    "id": "cas-a",
    "text": { "elementName": None  }, 
    "line": { "color": "rgba(5, 58, 133, 1)", "dash": None , "width": 2 },
    "area": { "color": "rgba(57, 130, 232, 1)" },
    "paperUrls": ["https://arxiv.org/abs/2012.05427"],
    "url": "../../data/BC1/NeutronStarCooling.csv",
    "curveType": "excluded",
    "categories": {
      "detectionType": "Indirect detection",
      "experimentType": "Astrophysical observations",
      "timeType": "Recent constraints",
      "assumption": "None",
    }, 
  },
  {
    "labelName": "Planck + unWISE", 
    "longName": "Planck + unWISE CMB", 
    "id": "planck-unwise",
    "text": { "elementName": None  }, 
    "line": { "color": "rgba(5, 58, 133, 1)", "dash": None , "width": 2 },
    "area": { "color": "rgba(57, 130, 232, 1)" },
    "paperUrls": ["https://arxiv.org/abs/2406.02546"],
    "url": "../../data/BC1/Planck_unWISE.csv",
    "curveType": "excluded",
    "categories": {
      "detectionType": "Indirect detection",
      "experimentType": "Astrophysical observations",
      "timeType": "Recent constraints",
      "assumption": "None",
    }, 
  },
  {
    "labelName": "Plimpton-Lawton", 
    "longName": "Plimpton-Lawton experiment", 
    "id": "plimpton-lawton",
    "text": { "elementName": None  }, 
    "line": { "color": "rgba(5, 58, 133, 1)", "dash": None , "width": 2 },
    "area": { "color": "rgba(57, 130, 232, 1)" },
    "paperUrls": ["https://arxiv.org/abs/2008.02209"],
    "url": "../../data/BC1/PlimptonLawton.csv",
    "curveType": "excluded",
    "categories": {
      "detectionType": "Direct detection",
      "experimentType": "Laboratory experiments",
      "timeType": "Recent constraints",
      "assumption": "None",
    }, 
  },
  {
    "labelName": "SENSEI", 
    "longName": "SENSEI", 
    "id": "sensei",
    "text": { "elementName": None  }, 
    "line": { "color": "rgba(5, 58, 133, 1)", "dash": None , "width": 2 },
    "area": { "color": "rgba(57, 130, 232, 1)" },
    "paperUrls": ["https://arxiv.org/abs/2004.11378"],
    "url": "../../data/BC1/SENSEI.csv",
    "curveType": "excluded",
    "categories": {
      "detectionType": "Direct detection",
      "experimentType": "Laboratory experiments",
      "timeType": "Recent constraints",
      "assumption": "None",
    }, 
  },
  {
    "labelName": "SHIPS", 
    "longName": "SHIPS", 
    "id": "ships",
    "text": { "elementName": None  }, 
    "line": { "color": "rgba(5, 58, 133, 1)", "dash": None , "width": 2 },
    "area": { "color": "rgba(57, 130, 232, 1)" },
    "paperUrls": ["https://arxiv.org/abs/1502.04490"],
    "url": "../../data/BC1/Planck_unWISE.csv",
    "curveType": "excluded",
    "categories": {
      "detectionType": "Direct detection",
      "experimentType": "Astrophysical observations",
      "timeType": "Recent constraints",
      "assumption": "None",
    }, 
  },
  {
    "labelName": "SNIPE", 
    "longName": "SNIPE Hunt", 
    "id": "snipe",
    "text": { "elementName": None  }, 
    "line": { "color": "rgba(5, 58, 133, 1)", "dash": None , "width": 2 },
    "area": { "color": "rgba(57, 130, 232, 1)" },
    "paperUrls": ["https://arxiv.org/abs/2306.11575"],
    "url": "../../data/BC1/SNIPE.csv",
    "curveType": "excluded",
    "categories": {
      "detectionType": "Direct detection",
      "experimentType": "Astrophysical observations",
      "timeType": "Recent constraints",
      "assumption": "None",
    }, 
  },
  {
    "labelName": "Solar", 
    "longName": "Solar", 
    "id": "solar",
    "text": { "elementName": None  }, 
    "line": { "color": "rgba(5, 58, 133, 1)", "dash": None , "width": 2 },
    "area": { "color": "rgba(57, 130, 232, 1)" },
    "paperUrls": ["https://arxiv.org/abs/2304.12907"],
    "url": "../../data/BC1/Solar.csv",
    "curveType": "excluded",
    "categories": {
      "detectionType": "Indirect detection",
      "experimentType": "Astrophysical observations",
      "timeType": "Recent constraints",
      "assumption": "None",
    }, 
  },
  {
    "labelName": "Spectroscopy", 
    "longName": "Spectroscopy", 
    "id": "spectroscopy",
    "text": { "elementName": None  }, 
    "line": { "color": "rgba(5, 58, 133, 1)", "dash": None , "width": 2 },
    "area": { "color": "rgba(57, 130, 232, 1)" },
    "paperUrls": ["https://arxiv.org/abs/1008.3536"],
    "url": "../../data/BC1/Spectroscopy.csv",
    "curveType": "excluded",
    "categories": {
      "detectionType": "Indirect detection",
      "experimentType": "Laboratory experiments",
      "timeType": "Past constraints",
      "assumption": "None",
    }, 
  },
  {
    "labelName": "SPring-8", 
    "longName": "SPring-8", 
    "id": "spring-8",
    "text": { "elementName": None  }, 
    "line": { "color": "rgba(5, 58, 133, 1)", "dash": None , "width": 2 },
    "area": { "color": "rgba(57, 130, 232, 1)" },
    "paperUrls": ["https://arxiv.org/abs/1301.6557"],
    "url": "../../data/BC1/SPring-8.csv",
    "curveType": "excluded",
    "categories": {
      "detectionType": "Direct detection",
      "experimentType": "Laboratory experiments",
      "timeType": "Past constraints",
      "assumption": "None",
    }, 
  },
  {
    "labelName": "SuperCDMS", 
    "longName": "SuperCDMS", 
    "id": "supercdms",
    "text": { "elementName": None  }, 
    "line": { "color": "rgba(5, 58, 133, 1)", "dash": None , "width": 2 },
    "area": { "color": "rgba(57, 130, 232, 1)" },
    "paperUrls": ["https://arxiv.org/abs/1911.11905"],
    "url": "../../data/BC1/SuperCDMS.csv",
    "curveType": "excluded",
    "categories": {
      "detectionType": "Direct detection",
      "experimentType": "Laboratory experiments",
      "timeType": "Recent constraints",
      "assumption": "Dark Matter",
    }, 
  },
  {
    "labelName": "SuperMAG", 
    "longName": "SuperMAG Combined", 
    "id": "supermag-combined",
    "text": { "elementName": None  }, 
    "line": { "color": "rgba(5, 58, 133, 1)", "dash": None , "width": 2 },
    "area": { "color": "rgba(57, 130, 232, 1)" },
    "paperUrls": [
      "https://arxiv.org/abs/2106.00022",
      "https://arxiv.org/abs/2408.16045",
      "https://arxiv.org/abs/2108.08852",
    ],
    "url": "../../data/BC1/SuperMAG_Combined.csv",
    "curveType": "excluded",
    "categories": {
      "detectionType": "Indirect detection",
      "experimentType": "Astrophysical observations",
      "timeType": "Recent constraints",
      "assumption": "None",
    }, 
  },
  {
    "labelName": "TEXONO", 
    "longName": "TEXONO", 
    "id": "texono",
    "text": { "elementName": None  }, 
    "line": { "color": "rgba(5, 58, 133, 1)", "dash": None , "width": 2 },
    "area": { "color": "rgba(57, 130, 232, 1)" },
    "paperUrls": ["https://arxiv.org/abs/1804.10777"],
    "url": "../../data/BC1/TEXONO.csv",
    "curveType": "excluded",
    "categories": {
      "detectionType": "Indirect detection",
      "experimentType": "Laboratory experiments",
      "timeType": "Recent constraints",
      "assumption": "None",
    }, 
  },
  {
    "labelName": "Tokyo", 
    "longName": "Tokyo-dish", 
    "id": "tokyo",
    "text": { "elementName": None  }, 
    "line": { "color": "rgba(5, 58, 133, 1)", "dash": None , "width": 2 },
    "area": { "color": "rgba(57, 130, 232, 1)" },
    "paperUrls": ["https://arxiv.org/abs/2003.13144"],
    "url": "../../data/BC1/Tokyo-Dish.csv",
    "curveType": "excluded",
    "categories": {
      "detectionType": "Direct detection",
      "experimentType": "Laboratory experiments",
      "timeType": "Recent constraints",
      "assumption": "None",
    }, 
  },
  {
    "labelName": "XENON1T S2", 
    "longName": "XENON1T S2", 
    "id": "xenon1t-s2",
    "text": { "elementName": None  }, 
    "line": { "color": "rgba(5, 58, 133, 1)", "dash": None , "width": 2 },
    "area": { "color": "rgba(57, 130, 232, 1)" },
    "paperUrls": ["https://arxiv.org/abs/1907.11485"],
    "url": "../../data/BC1/Xenon1T.csv",
    "curveType": "excluded",
    "categories": {
      "detectionType": "Direct detection",
      "experimentType": "Laboratory experiments",
      "timeType": "Recent constraints",
      "assumption": "None",
    }, 
  },
  {
    "labelName": "XENON1T S2S1", 
    "longName": "XENON1T S2S1", 
    "id": "xenon1t-s2s1",
    "text": { "elementName": None  }, 
    "line": { "color": "rgba(5, 58, 133, 1)", "dash": None , "width": 2 },
    "area": { "color": "rgba(57, 130, 232, 1)" },
    "paperUrls": ["https://arxiv.org/abs/2006.09721"],
    "url": "../../data/BC1/Xenon1T_S1S2.csv",
    "curveType": "excluded",
    "categories": {
      "detectionType": "Direct detection",
      "experimentType": "Laboratory experiments",
      "timeType": "Recent constraints",
      "assumption": "None",
    }, 
  },
  {
    "labelName": "XENON1T SE", 
    "longName": "XENON1T SE", 
    "id": "xenon1t-se",
    "text": { "elementName": None  }, 
    "line": { "color": "rgba(5, 58, 133, 1)", "dash": None , "width": 2 },
    "area": { "color": "rgba(57, 130, 232, 1)" },
    "paperUrls": ["https://arxiv.org/abs/2112.12116"],
    "url": "../../data/BC1/XENON1T_SE.csv",
    "curveType": "excluded",
    "categories": {
      "detectionType": "Direct detection",
      "experimentType": "Laboratory experiments",
      "timeType": "Recent constraints",
      "assumption": "None",
    }, 
  },
  {
    "labelName": "XENON1T Solar S2", 
    "longName": "XENON1T Solar S2", 
    "id": "xenon1t-solar-s2",
    "text": { "elementName": None  }, 
    "line": { "color": "rgba(5, 58, 133, 1)", "dash": None , "width": 2 },
    "area": { "color": "rgba(57, 130, 232, 1)" },
    "paperUrls": ["https://arxiv.org/abs/2006.13929"],
    "url": "../../data/BC1/XENON1T_Solar_S2.csv",
    "curveType": "excluded",
    "categories": {
      "detectionType": "Direct detection",
      "experimentType": "Laboratory experiments",
      "timeType": "Recent constraints",
      "assumption": "None",
    }, 
  },
  {
    "labelName": "XENONnT", 
    "longName": "XENONnT", 
    "id": "xenonnt",
    "text": { "elementName": None  }, 
    "line": { "color": "rgba(5, 58, 133, 1)", "dash": None , "width": 2 },
    "area": { "color": "rgba(57, 130, 232, 1)" },
    "paperUrls": ["https://arxiv.org/abs/2207.11330"],
    "url": "../../data/BC1/XENONnT.csv",
    "curveType": "excluded",
    "categories": {
      "detectionType": "Direct detection",
      "experimentType": "Laboratory experiments",
      "timeType": "Recent constraints",
      "assumption": "None",
    }, 
  },
  {
    "labelName": "SHiP", 
    "longName": "SHiP", 
    "id": "ship",
    "text": { "elementName": None  }, 
    "line": { "color": "rgba(5, 58, 133, 1)", "dash": "20,7", "width": 2 },
    "area": { "color": None  },
    "paperUrls": ["https://arxiv.org/abs/2504.06692v1"],
    "url": "../../data/BC1/SHiP_rescaled.csv",
    "curveType": "projection",
    "categories": {
      "detectionType": "Direct detection",
      "experimentType": "Collider experiments",
      "timeType": "Planned/future constraints",
      "assumption": "None",
    },  
  },
  {
    "labelName": "HIKE", 
    "longName": "HIKE", 
    "id": "hike",
    "text": { "elementName": None  }, 
    "line": { "color": "rgba(5, 58, 133, 1)", "dash": "20,7", "width": 2 },
    "area": { "color": None  },
    "paperUrls": ["https://arxiv.org/abs/2311.08231"],
    "url": "../../data/BC1/HIKE.csv",
    "curveType": "projection",
    "categories": {
      "detectionType": "Direct detection",
      "experimentType": "Collider experiments",
      "timeType": "Planned/future constraints",
      "assumption": "None",
    }, 
  },
  {
    "labelName": "CHARM", 
    "longName": "CHARM", 
    "id": "charm",
    "text": { "elementName": None  }, 
    "line": { "color": "rgba(5, 58, 133, 1)", "dash": None , "width": 2 },
    "area": { "color": "rgba(57, 130, 232, 1)" },
    "paperUrls": ["https://arxiv.org/abs/1204.3583"],
    "url": "../../data/BC1/CHARM.csv",
    "curveType": "excluded",
    "categories": {
      "detectionType": "Direct detection",
      "experimentType": "Collider experiments",
      "timeType": "Past constraints",
      "assumption": "None",
    }, 
  },
  {
    "labelName": "NA64(e)", 
    "longName": "NA64(e)", 
    "id": "na64e",
    "text": { "elementName": None  }, 
    "line": { "color": "rgba(5, 58, 133, 1)", "dash": "20,7", "width": 2 },
    "area": { "color": None  },
    "paperUrls": ["https://arxiv.org/abs/1204.3583"],
    "url": "../../data/BC1/NA64(e).csv",
    "curveType": "projection",
    "categories": {
      "detectionType": "Direct detection",
      "experimentType": "Collider experiments",
      "timeType": "Planned/future constraints",
      "assumption": "None",
    }, 
  },
  {
    "labelName": "DarkQuest (2023)", 
    "longName": "DarkQuest (2023)", 
    "id": "darkquest-2023",
    "text": { "elementName": None  }, 
    "line": { "color": "rgba(5, 58, 133, 1)", "dash": "20,7", "width": 2 },
    "area": { "color": None  },
    "paperUrls": ["https://arxiv.org/abs/2203.08322"],
    "url": "../../data/BC1/DarkQuest(2023).csv",
    "curveType": "projection",
    "categories": {
      "detectionType": "Direct detection",
      "experimentType": "Collider experiments",
      "timeType": "Planned/future constraints",
      "assumption": "None",
    }, 
  },
  {
    "labelName": "DarkQuest (2026+)", 
    "longName": "DarkQuest (2026+)", 
    "id": "arkquest-2026",
    "text": { "elementName": None  }, 
    "line": { "color": "rgba(5, 58, 133, 1)", "dash": "20,7", "width": 2 },
    "area": { "color": None  },
    "paperUrls": ["https://arxiv.org/abs/2203.08322"],
    "url": "../../data/BC1/DarkQuest(2026).csv",
    "curveType": "projection",
    "categories": {
      "detectionType": "Direct detection",
      "experimentType": "Collider experiments",
      "timeType": "Planned/future constraints",
      "assumption": "None",
    }, 
  },
  {
    "labelName": "FACET", 
    "longName": "FACET", 
    "id": "facet",
    "text": { "elementName": None  }, 
    "line": { "color": "rgba(5, 58, 133, 1)", "dash": "20,7", "width": 2 },
    "area": { "color": None  },
    "paperUrls": ["https://arxiv.org/abs/2201.00019"],
    "url": "../../data/BC1/FACET.csv",
    "curveType": "projection",
    "categories": {
      "detectionType": "Direct detection",
      "experimentType": "Collider experiments",
      "timeType": "Planned/future constraints",
      "assumption": "None",
    }, 
  },
  {
    "labelName": "FASER (57fb)", 
    "longName": "FASER (57fb)", 
    "id": "faser-57",
    "text": { "elementName": None  }, 
    "line": { "color": "rgba(5, 58, 133, 1)", "dash": None , "width": 2 },
    "area": { "color": "rgba(57, 130, 232, 1)" },
    "paperUrls": ["https://arxiv.org/abs/2410.10363"],
    "url": "../../data/BC1/FASER(58fb).csv",
    "curveType": "excluded",
    "categories": {
      "detectionType": "Direct detection",
      "experimentType": "Collider experiments",
      "timeType": "Recent constraints",
      "assumption": "None",
    }, 
  },
  {
    "labelName": "NA62", 
    "longName": "NA62", 
    "id": "na62",
    "text": { "elementName": None  }, 
    "line": { "color": "rgba(5, 58, 133, 1)", "dash": None , "width": 2 },
    "area": { "color": "rgba(57, 130, 232, 1)" },
    "paperUrls": ["https://arxiv.org/abs/2502.04241"],
    "url": "../../data/BC1/NA62.csv",
    "curveType": "excluded",
    "categories": {
      "detectionType": "Direct detection",
      "experimentType": "Collider experiments",
      "timeType": "Recent constraints",
      "assumption": "None",
    }, 
  },
  {
    "labelName": "E774", 
    "longName": "E774", 
    "id": "e774",
    "text": { "elementName": None  }, 
    "line": { "color": "rgba(5, 58, 133, 1)", "dash": None , "width": 2 },
    "area": { "color": "rgba(57, 130, 232, 1)" },
    "paperUrls": ["https://arxiv.org/abs/1802.03794"],
    "url": "../../data/BC1/E774.csv",
    "curveType": "excluded",
    "categories": {
      "detectionType": "Direct detection",
      "experimentType": "Collider experiments",
      "timeType": "Past constraints",
      "assumption": "None",
    }, 
  },
  {
    "labelName": "E141", 
    "longName": "E141", 
    "id": "e141",
    "text": { "elementName": None  }, 
    "line": { "color": "rgba(5, 58, 133, 1)", "dash": None , "width": 2 },
    "area": { "color": "rgba(57, 130, 232, 1)" },
    "paperUrls": ["https://arxiv.org/abs/1802.03794"],
    "url": "../../data/BC1/E141.csv",
    "curveType": "excluded",
    "categories": {
      "detectionType": "Direct detection",
      "experimentType": "Collider experiments",
      "timeType": "Past constraints",
      "assumption": "None",
    }, 
  },
  {
    "labelName": "Orsay", 
    "longName": "Orsay", 
    "id": "orsay",
    "text": { "elementName": None  }, 
    "line": { "color": "rgba(5, 58, 133, 1)", "dash": None , "width": 2 },
    "area": { "color": "rgba(57, 130, 232, 1)" },
    "paperUrls": ["https://arxiv.org/abs/1802.03794"],
    "url": "../../data/BC1/Orsay.csv",
    "curveType": "excluded",
    "categories": {
      "detectionType": "Direct detection",
      "experimentType": "Collider experiments",
      "timeType": "Past constraints",
      "assumption": "None",
    }, 
  },
  {
    "labelName": "E137", 
    "longName": "E137", 
    "id": "e137",
    "text": { "elementName": None  }, 
    "line": { "color": "rgba(5, 58, 133, 1)", "dash": None , "width": 2 },
    "area": { "color": "rgba(57, 130, 232, 1)" },
    "paperUrls": ["https://arxiv.org/abs/1802.03794"],
    "url": "../../data/BC1/E137.csv",
    "curveType": "excluded",
    "categories": {
      "detectionType": "Direct detection",
      "experimentType": "Collider experiments",
      "timeType": "Past constraints",
      "assumption": "None",
    }, 
  },
  {
    "labelName": "A1", 
    "longName": "A1", 
    "id": "a1",
    "text": { "elementName": None  }, 
    "line": { "color": "rgba(5, 58, 133, 1)", "dash": None , "width": 2 },
    "area": { "color": "rgba(57, 130, 232, 1)" },
    "paperUrls": ["https://arxiv.org/abs/1404.5502"],
    "url": "../../data/BC1/A1_rescaled.csv",
    "curveType": "excluded",
    "categories": {
      "detectionType": "Direct detection",
      "experimentType": "Collider experiments",
      "timeType": "Past constraints",
      "assumption": "None",
    }, 
  },
  {
    "labelName": "FASER (Run 3)", 
    "longName": "FASER (Run 3)", 
    "id": "faser-run3",
    "text": { "elementName": None  }, 
    "line": { "color": "rgba(5, 58, 133, 1)", "dash": "20,7", "width": 2 },
    "area": { "color": None  },
    "paperUrls": ["https://arxiv.org/abs/2203.05090"],
    "url": "../../data/BC1/FASER(Run3).csv",
    "curveType": "projection",
    "categories": {
      "detectionType": "Direct detection",
      "experimentType": "Collider experiments",
      "timeType": "Planned/future constraints",
      "assumption": "None",
    }, 
  },
  {
    "labelName": "FASER (HL-LHC)", 
    "longName": "FASER (HL-LHC)", 
    "id": "faser-hl-lhc",
    "text": { "elementName": None  }, 
    "line": { "color": "rgba(5, 58, 133, 1)", "dash": "20,7", "width": 2 },
    "area": { "color": None  },
    "paperUrls": ["https://arxiv.org/abs/2203.05090"],
    "url": "../../data/BC1/FASER(HL-LHC).csv",
    "curveType": "projection",
    "categories": {
      "detectionType": "Direct detection",
      "experimentType": "Collider experiments",
      "timeType": "Planned/future constraints",
      "assumption": "None",
    }, 
  },
  {
    "labelName": "LHCb", 
    "longName": "LHCb", 
    "id": "lhcb",
    "text": { "elementName": None  }, 
    "line": { "color": "rgba(5, 58, 133, 1)", "dash": None , "width": 2 },
    "area": { "color": "rgba(57, 130, 232, 1)" },
    "paperUrls": ["https://arxiv.org/abs/1910.06926"],
    "url": "../../data/BC1/LHCb_rescaled.csv",
    "curveType": "excluded",
    "categories": {
      "detectionType": "Direct detection",
      "experimentType": "Collider experiments",
      "timeType": "Recent constraints",
      "assumption": "None",
    }, 
  },
  {
    "labelName": "(g-2)e", 
    "longName": "(g-2)e", 
    "id": "g-2-e",
    "text": { "elementName": None  }, 
    "line": { "color": "rgba(5, 58, 133, 1)", "dash": None , "width": 2 },
    "area": { "color": "rgba(57, 130, 232, 1)" },
    "paperUrls": [
      "https://arxiv.org/abs/0811.1030",
      "https://arxiv.org/abs/1209.2558",
    ],
    "url": "../../data/BC1/g-2e_updated_rescaled.csv",
    "curveType": "excluded",
    "categories": {
      "detectionType": "Direct detection",
      "experimentType": "Collider experiments",
      "timeType": "Past constraints",
      "assumption": "None",
    }, 
  },
  {
    "labelName": "nu-Cal", 
    "longName": "nu-Cal", 
    "id": "nu-cal",
    "text": { "elementName": None  }, 
    "line": { "color": "rgba(5, 58, 133, 1)", "dash": None , "width": 2 },
    "area": { "color": "rgba(57, 130, 232, 1)" },
    "paperUrls": ["https://arxiv.org/abs/1311.3870"],
    "url": "../../data/BC1/nu-Cal.csv",
    "curveType": "excluded",
    "categories": {
      "detectionType": "Direct detection",
      "experimentType": "Collider experiments",
      "timeType": "Past constraints",
      "assumption": "None",
    }, 
  },
  {
    "labelName": "Mu3e (Phase 1)", 
    "longName": "Mu3e (Phase 1)", 
    "id": "mu3e-phase1",
    "text": { "elementName": None  }, 
    "line": { "color": "rgba(5, 58, 133, 1)", "dash": "20,7", "width": 2 },
    "area": { "color": None  },
    "paperUrls": ["https://arxiv.org/abs/1411.1770"],
    "url": "../../data/BC1/Mu3e(Phase1)_rescaled.csv",
    "curveType": "projection",
    "categories": {
      "detectionType": "Direct detection",
      "experimentType": "Collider experiments",
      "timeType": "Planned/future constraints",
      "assumption": "None",
    }, 
  },
  {
    "labelName": "Mu3e (Phase 2)", 
    "longName": "Mu3e (Phase 2)", 
    "id": "mu3e-phase2",
    "text": { "elementName": None  }, 
    "line": { "color": "rgba(5, 58, 133, 1)", "dash": "20,7", "width": 2 },
    "area": { "color": None  },
    "paperUrls": ["https://arxiv.org/abs/1411.1770"],
    "url": "../../data/BC1/Mu3e(Phase2)_rescaled.csv",
    "curveType": "projection",
    "categories": {
      "detectionType": "Direct detection",
      "experimentType": "Collider experiments",
      "timeType": "Planned/future constraints",
      "assumption": "None",
    }, 
  },
  {
    "labelName": "NA48/2", 
    "longName": "NA48/2", 
    "id": "na48-2",
    "text": { "elementName": None  }, 
    "line": { "color": "rgba(5, 58, 133, 1)", "dash": None , "width": 2 },
    "area": { "color": "rgba(57, 130, 232, 1)" },
    "paperUrls": ["https://arxiv.org/abs/1504.00607"],
    "url": "../../data/BC1/NA48-2_rescaled.csv",
    "curveType": "excluded",
    "categories": {
      "detectionType": "Direct detection",
      "experimentType": "Collider experiments",
      "timeType": "Recent constraints",
      "assumption": "None",
    }, 
  },
  {
    "labelName": "KLOE combined", 
    "longName": "KLOE combined", 
    "id": "kloe",
    "text": { "elementName": None  }, 
    "line": { "color": "rgba(5, 58, 133, 1)", "dash": None , "width": 2 },
    "area": { "color": "rgba(57, 130, 232, 1)" },
    "paperUrls": ["https://arxiv.org/abs/1603.06086"],
    "url": "../../data/BC1/KLOE_combined_rescaled.csv",
    "curveType": "excluded",
    "categories": {
      "detectionType": "Direct detection",
      "experimentType": "Collider experiments",
      "timeType": "Recent constraints",
      "assumption": "None",
    }, 
  },
  {
    "labelName": "SN1987A", 
    "longName": "SN1987A", 
    "id": "sn1987a",
    "text": { "elementName": None  }, 
    "line": { "color": "rgba(5, 58, 133, 1)", "dash": None , "width": 2 },
    "area": { "color": "rgba(57, 130, 232, 1)" },
    "paperUrls": ["https://arxiv.org/abs/1611.03864"],
    "url": "../../data/BC1/SN1987A.csv",
    "curveType": "excluded",
    "categories": {
      "detectionType": "Indirect detection",
      "experimentType": "Astrophysical observations",
      "timeType": "Recent constraints",
      "assumption": "None",
    }, 
  },
  {
    "labelName": "LDMX combined", 
    "longName": "LDMX combined", 
    "id": "ldmx-combined",
    "text": { "elementName": None  }, 
    "line": { "color": "rgba(5, 58, 133, 1)", "dash": "20,7", "width": 2 },
    "area": { "color": None  },
    "paperUrls": ["https://arxiv.org/abs/1807.01730"],
    "url": "../../data/BC1/LDMX_combined.csv",
    "curveType": "projection",
    "categories": {
      "detectionType": "Direct detection",
      "experimentType": "Collider experiments",
      "timeType": "Planned/future constraints",
      "assumption": "None",
    }, 
  },
  {
    "labelName": "MESA", 
    "longName": "MESA", 
    "id": "mesa",
    "text": { "elementName": None  }, 
    "line": { "color": "rgba(5, 58, 133, 1)", "dash": "20,7", "width": 2 },
    "area": { "color": None  },
    "paperUrls": ["https://arxiv.org/abs/1908.07921"],
    "url": "../../data/BC1/MESA.csv",
    "curveType": "projection",
    "categories": {
      "detectionType": "Direct detection",
      "experimentType": "Collider experiments",
      "timeType": "Planned/future constraints",
      "assumption": "None",
    }, 
  },
  {
    "labelName": "Gamma Factory (20MeV)", 
    "longName": "Gamma Factory (20MeV)", 
    "id": "gamma-factory-20mev",
    "text": { "elementName": None  }, 
    "line": { "color": "rgba(5, 58, 133, 1)", "dash": "20,7", "width": 2 },
    "area": { "color": None  },
    "paperUrls": ["https://arxiv.org/abs/2105.10289"],
    "url": "../../data/BC1/Gamma Factory (20MeV).csv",
    "curveType": "projection",
    "categories": {
      "detectionType": "Direct detection",
      "experimentType": "Collider experiments",
      "timeType": "Planned/future constraints",
      "assumption": "None",
    }, 
  },
  {
    "labelName": "Gamma Factory (200MeV)", 
    "longName": "Gamma Factory (200MeV)", 
    "id": "gamma-factory-200mev",
    "text": { "elementName": None  }, 
    "line": { "color": "rgba(5, 58, 133, 1)", "dash": "20,7", "width": 2 },
    "area": { "color": None  },
    "paperUrls": ["https://arxiv.org/abs/2105.10289"],
    "url": "../../data/BC1/Gamma Factory (200MeV).csv",
    "curveType": "projection",
    "categories": {
      "detectionType": "Direct detection",
      "experimentType": "Collider experiments",
      "timeType": "Planned/future constraints",
      "assumption": "None",
    }, 
  },
  {
    "labelName": "Gamma Factory (1600MeV)", 
    "longName": "Gamma Factory (1600MeV)", 
    "id": "gamma-factory-1600mev",
    "text": { "elementName": None  }, 
    "line": { "color": "rgba(5, 58, 133, 1)", "dash": "20,7", "width": 2 },
    "area": { "color": None  },
    "paperUrls": ["https://arxiv.org/abs/2105.10289"],
    "url": "../../data/BC1/Gamma Factory (1600MeV).csv",
    "curveType": "projection",
    "categories": {
      "detectionType": "Direct detection",
      "experimentType": "Collider experiments",
      "timeType": "Planned/future constraints",
      "assumption": "None",
    }, 
  },
  {
    "labelName": "CMS", 
    "longName": "CMS", 
    "id": "cms",
    "text": { "elementName": None  }, 
    "line": { "color": "rgba(5, 58, 133, 1)", "dash": None , "width": 2 },
    "area": { "color": "rgba(57, 130, 232, 1)" },
    "paperUrls": ["https://arxiv.org/abs/2309.16003"],
    "url": "../../data/BC1/CMS_rescaled.csv",
    "curveType": "excluded",
    "categories": {
      "detectionType": "Direct detection",
      "experimentType": "Collider experiments",
      "timeType": "Recent constraints",
      "assumption": "None",
    }, 
  },
]

# ---- 2) Loop through curves and create JSON files ----
for curve in plotData:
    url = curve["url"]  # CSV file path
    directory = os.path.dirname(url)
    base = os.path.splitext(os.path.basename(url))[0]
    json_path = os.path.join(directory, base + ".json")

    # Exclude the "url" itself from JSON (optional)
    curve_copy = {k: v for k, v in curve.items()}

    os.makedirs(directory, exist_ok=True)  # make sure dir exists
    with open(json_path, "w", encoding="utf-8") as f:
        json.dump(curve_copy, f, indent=2, ensure_ascii=False)

    print(f"✅ Saved {json_path}")
